# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11menXAsfJ9e-tOM9_kYeDL_GiW2gGG9w
"""

#Accion
class Accion:

  def __init__(self, ID, nombre, tipo, precio):
    self.ID = ID
    self.nombre = nombre
    self.tipo = tipo
    self.precio = precio
    self.precio_anterior = precio

  def actualizar_precio(self, nuevo_precio):
    self.precio_anterior = self.precio
    self.precio = nuevo_precio

  def calcular_cambio_porcentual(self):
    cambio = ((self.precio - self.precio_anterior) / self.precio_anterior) * 100
    return cambio

  def mostrar_informacion(self):
    print(f"{self.ID}, {self.nombre}, {self.tipo} - ${self.precio}")

  def estado(self):
    cambio = self.calcular_cambio_porcentual()
    if cambio > 0:
      return "En subida 📈"
    elif cambio < 0:
      return "En bajada 📉"
    else:
      return "Sin cambios"

accion1 = Accion(1, "Apple", 180, "Tecnología")

accion1.mostrar_informacion()

accion1.actualizar_precio(200)

print("Cambio porcentual:", accion1.calcular_cambio_porcentual())
print("Estado:", accion1.estado())

#Menu
class Menu:
  def iniciar(self):
    accion = Accion(1, "Apple", 180, "Tecnologia")

    while True:
      print("\nMENU")
      print("1. Ver informacion")
      print("2. Actualizar precio")
      print("3. Estado")
      print("4. Salir")

      opcion = input("Opcion: ")

      if opcion == "1":
        accion.mostrar_informacion()

      elif opcion == "2":
        nuevo = float(input("Nuevo precio: "))
        accion.actualizar_precio(nuevo)
        print("Precio actualizado")

      elif opcion == "3":
        print("Precio anterior:", accion1.precio_anterior)
        print("Cambio porcentual:", accion1.calcular_cambio_porcentual())
        print("Estado:", accion.estado())

      elif opcion == "4":
        break

      else:
        print("Opcion invalida")

menu = Menu()
menu.iniciar()