# -*- coding: utf-8 -*-
"""Tarea4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o65Xv0u0kfOybOiYTO79Vyn_LmyiiGEC
"""

class Expresion:
  def _convertir(self, valor):
    return Numero(valor) if isinstance(valor, (int, float)) else valor

  def __add__(self, otro):
    return Suma(self, otro)
  def __sub__(self, otro):
    return Resta(self, otro)
  def __mul__(self, otro):
    return Producto(self, otro)
  def __pow__(self, otro):
    return Potencia(self, otro)

  def __radd__(self, otro):
    return Suma(otro, self)
  def __rsub__(self, otro):
    return Resta(otro, self)
  def __rmul__(self, otro):
    return Producto(otro, self)
  def __rpow__(self, otro):
    return Potencia(otro, self)

class OperacionBinaria(Expresion):
  def __init__(self, izq, der):
    self.izq = self._convertir(izq)
    self.der = self._convertir(der)

class Numero(Expresion):
  def __init__(self, valor):
    self.valor = valor

  def latex(self):
    return str(self.valor)

  def evaluar(self, variables=None):
    return self.valor

  def _repr_latex_(self):
    return f"$${self.latex()}$$"

class Variable(Expresion):
  def __init__(self, nombre):
    self.nombre = nombre

  def latex(self):
    if len(self.nombre) > 1:
      return f"\\{self.nombre}"
    return self.nombre

  def evaluar(self, variables = None):
    if variables and self.nombre in variables:
      return variables[self.nombre]
    raise ValueError(f"Variable '{self.nombre}' no definida")

  def _repr_latex_(self):
    return f"$${self.latex()}$$"

class Suma(OperacionBinaria):
  def latex(self):
    return f"{self.izq.latex()} + {self.der.latex()}"

  def evaluar(self, variables=None):
    return self.izq.evaluar(variables) + self.der.evaluar(variables)

  def _repr_latex_(self):
    return f"$${self.latex()}$$"

class Resta(OperacionBinaria):
  def latex(self):
    return f"{self.izq.latex()} - {self.der.latex()}"

  def evaluar(self, variables=None):
    return self.izq.evaluar(variables) - self.der.evaluar(variables)

  def _repr_latex_(self):
    return f"$${self.latex()}$$"

class Producto(OperacionBinaria):
  def latex(self):
    izq = self.izq.latex()
    der = self.der.latex()

    if isinstance(self.izq, (Suma, Resta)):
      izq = f"({izq})"
    if isinstance(self.der, (Suma, Resta)):
      der = f"({der})"

    return f"{izq} \\cdot {der}"

  def evaluar(self, variables=None):
    return self.izq.evaluar(variables) * self.der.evaluar(variables)

  def _repr_latex_(self):
    return f"$${self.latex()}$$"

class Potencia(OperacionBinaria):
  def __init__(self, base, exponente):
    super().__init__(base, exponente)

  def latex(self):
    base = self.izq.latex()

    if isinstance(self.izq, (Suma, Resta)):
      base = f"({base})"

    if isinstance(self.der, (Suma, Resta)):
      exp = f"({self.der.latex()})"
    else:
      exp = self.der.latex()

    return f"{base}^{{{exp}}}"

  def evaluar(self, variables=None):
    return self.izq.evaluar(variables) ** self.der.evaluar(variables)

  def _repr_latex_(self):
    return f"$${self.latex()}$$"

#Probando el sistema:

x = Variable("x")
expr = (x + 2) * (x - 3)

expr.latex()
# "(x + 2) \cdot (x - 3)"

expr.evaluar({"x": 5})
# (5+2)*(5-3) = 14

expr

