# -*- coding: utf-8 -*-
"""Tarea5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18JYtEL7QB0NlJa8NWCYuTgL-je6u98k8
"""

# Diccionario de conversiones
conversiones = {
    "A+": 4.0,
    "A": 4.0,
    "A-": 3.7,
    "B+": 3.3,
    "B": 3.0,
    "B-": 2.7,
    "C+": 2.3,
    "C": 2.0,
    "C-": 1.7,
    "D+": 1.3,
    "D": 1.0,
    "F": 0.0
}

inverso = {}
for letra, puntos in conversiones.items():
    if puntos not in inverso:
        inverso[puntos] = letra

while True:
    entrada = input("Ingrese una calificación (o Enter para salir): ")

    if entrada == "":
        break

    try:
        puntos = float(entrada)

        if puntos in inverso:
            print("Calificación con letra:", inverso[puntos])
        else:
            print("Entrada no válida.")

    except ValueError:
        entrada = entrada.upper()

        if entrada in conversiones:
            print("Puntos de calificación:", conversiones[entrada])
        else:
            print("Entrada no válida.")

