# -*- coding: utf-8 -*-
"""Tarea 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19xp4MM3r3Y8mGCW9buMtwAEA_nsylTH7
"""

with open("texto.txt", "w", encoding="utf-8") as archivo:
    archivo.write("""Este es un ejemplo ejemplo de texto.
La palabra palabra está repetida.
Hola
hola mundo.
""")

with open("texto1.txt", "w", encoding="utf-8") as archivo:
    archivo.write("""Hoy fui fui al mercado.
Compré pan y y leche.
El perro
perro ladró toda la noche.
""")

import string

nombre_archivo = input()

try:
    archivo = open(nombre_archivo, "r", encoding="utf-8")

    palabra_anterior = ""
    linea_numero = 0

    for linea in archivo:
        linea_numero += 1

        for signo in string.punctuation:
            linea = linea.replace(signo, " ")

        palabras = linea.lower().split()

        for palabra in palabras:

            if palabra == palabra_anterior:
                print(f"Palabra repetida en la línea {linea_numero}: '{palabra}'")

            palabra_anterior = palabra

    archivo.close()

except FileNotFoundError:
    print("Error: El archivo no existe.")

except Exception as e:
    print("Error durante el procesamiento del archivo:")
    print(e)

